siteTitle = "Pages Halwax"
siteAuthor = "Michael Halwax"
siteDescr = "Passionate software developer with special interest on tool development and API design."

siteGithubUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/halwax"